language: go

go:
  - 1.11.x

env:
  - GO111MODULE=on 

addons:
   apt:
      packages:
         - libx11-dev xorg-dev
         - libxtst-dev libpng++-dev
         - xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
        #  - libusb-dev
         - libxkbcommon-dev
         - xsel
         - xclip
         - appindicator3-0.1

# Don't email me the results of the test runs.
notifications:
  email: false

before_install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -t -v ./...

script:
  - go test -v -failfast -race ./...