name: Go

on: [push, pull_request]

jobs:

  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.25.3

    - name: Test
      run: go test -v ./...
